# Generated by Django 4.2.2 on 2023-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
