# Generated by Django 4.2.2 on 2023-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
