# Generated by Django 4.2.2 on 2023-06-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_aplly'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplly',
            new_name='Apply',
        ),
    ]
