# Generated by Django 4.2.2 on 2023-06-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_rename_aplly_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='phone',
            field=models.IntegerField(help_text='Contact phone number'),
        ),
    ]
