# Generated by Django 4.2.2 on 2023-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Blog_Title')),
                ('text', models.TextField(verbose_name='Blog_Text')),
                ('image', models.ImageField(upload_to='media/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=1)),
                ('title2', models.CharField(max_length=80, null=True, verbose_name='Blog_Title1')),
                ('text2', models.TextField(null=True, verbose_name='Blog_Text2')),
                ('image2', models.ImageField(null=True, upload_to='media/')),
                ('title3', models.CharField(max_length=80, null=True, verbose_name='Blog_Title3')),
                ('text3', models.TextField(null=True, verbose_name='Blog_Text3')),
                ('image3', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
