# Generated by Django 4.2.2 on 2023-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cards_exctra_title_alter_cards_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_titles',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
