# Generated by Django 4.2.2 on 2023-06-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('employers', models.IntegerField()),
                ('youngers', models.FloatField()),
                ('higher_education', models.IntegerField()),
                ('specialist_in_banking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Success_Histories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
