# Generated by Django 4.2.2 on 2023-06-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Success_Histories',
            new_name='Success_stories',
        ),
    ]
