# Generated by Django 4.2.2 on 2023-06-21 11:07

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='card_title')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='card_title2')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('letter', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='slider_title')),
                ('text', models.CharField(max_length=255, verbose_name='slider_video')),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='cards_title')),
                ('exctra_title', models.CharField(blank=True, max_length=32, null=True, verbose_name='title_title')),
                ('icon', models.ImageField(upload_to='media/')),
                ('card_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card_titles')),
            ],
        ),
    ]
