# Generated by Django 4.2.2 on 2023-06-22 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cards_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.card_titles'),
        ),
    ]
