# Generated by Django 4.2.2 on 2023-06-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cards_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_title', to='main.card_titles'),
        ),
    ]
